server: 
  port: 9050  
  session-timeout: 30
  compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
      min-response-size: 128  #byte 大于128 压缩

  output:
    ansi:
      enabled: ALWAYS

spring:
  redis:
    database: 15
    host:
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 1

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fancv.entity


age: 18
name: jason-dev
manInfo: "age:${age},name:${name}"

config:
  name: "hamish"
  age: 14

